version: "3"
services:
  database:
    image: postgres:11-alpine
    environment:
      - POSTGRES_DB=dev-news
      - POSTGRES_USER=dev-news_user
      - POSTGRES_PASSWORD=dev-news_pass
    ports:
      - "5433:5432"
    volumes:
      - db-data:/var/lib/posgresql/data
volumes:
  db-data: